export { Boton } from './Boton'
export type { PropsBoton, VarianteBoton } from './Boton'
export { Tabs } from './Tabs'
export type { Pestaña, PropsTabs } from './Tabs'
export { Spinner } from './Spinner'
export type { PropsSpinner } from './Spinner'
export { ErrorCard } from './ErrorCard'
export type { ErrorPersonalizado, PropsErrorCard } from './ErrorCard'
export { Card, CardHeader } from './Card'
export type { PropsCard, PropsCardHeader } from './Card'
export { Badge } from './Badge'
export type { PropsBadge, VarianteBadge } from './Badge'
export { Avatar } from './Avatar'
export type { PropsAvatar } from './Avatar'
export { DetalleFila, DetalleItem } from './DetalleGrid'
export type { DetalleFilaProps, DetalleItemProps } from './DetalleGrid'

